# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: Random Number Generator Challenge-1111
short_description: Random number generation challenge for each submission
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras egestas a libero nec sagittis.
evaluation_script: evaluation_script.zip
remote_evaluation: False
start_date: 2019-01-01 00:00:00
end_date: 2099-05-31 23:59:59
published: True
tags: 
  - random-number-generation
  - machine-learning
  - data-science
  - computer-vision
leaderboard:
  - id: 1
    schema:
      {
        "labels": ["ACC"],
        "default_order_by": "ACC",
        "metadata": {
        }
      }

challenge_phases:
  - id: 1
    name: VG-RS
    description: templates/challenge_phase_1_description.html
    leaderboard_public: False
    is_public: False
    challenge: 1
    is_active: True
    max_concurrent_submissions_allowed: 3
    allowed_email_ids: []
    disable_logs: False
    is_submission_public: True
    start_date: 2019-01-19 00:00:00
    end_date: 2099-04-25 23:59:59
    test_annotation_file: annotations/test_annotations_devsplit.json
    codename: VG-RS
    max_submissions_per_day: 5000
    max_submissions_per_month: 5000
    max_submissions: 5000
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json, .zip, .txt, .tsv, .gz, .csv, .h5, .npy, .npz"

dataset_splits:
  - id: 1
    name: Train Split
    codename: train_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 1
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
    show_execution_time: True
    show_leaderboard_by_latest_submission: True
